framework:
    workflows:
        fidelity_cards:
            type: 'workflow'
            marking_store:
                type: 'single_state'
                arguments:
                    - 'state'
            supports:
                - App\Entity\Card
            places:
                - create
                - free
                - affected
                - pre_active
                - active
            transitions:
                created:
                    from: create
                    to:   free
                distribute:
                    from: free
                    to:   affected
                pre_activation:
                    from: affected
                    to:   pre_active
                activation:
                    from: pre_active
                    to:   active


